#!/bin/bash
set -e
SpriteSize=16
# `montage` is from ImageMagick
#pages='sprites/*.*'
pages='sprites/*.svg sprites/*.png'
montage $pages -crop "${SpriteSize}x${SpriteSize}" -format "%p %t\n" -identify -geometry "${SpriteSize}x${SpriteSize}+0+0!" -background "#00000000" sprites.png | \
    awk 'BEGIN { print "--autogenerated, do not edit\n" "spritepage = {}" } { if (! ($2 in seen)) { print "spritepage[\"" $2 "\"] = ", ($1 + 1) } seen[$2] = $1 }' > spritepage.lua
